package configstore

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"net/url"
	"strings"
	"time"

	"github.com/ranklancer/bulwark/pkg/types"
)

// NotifierKind tags the underlying channel implementation. Adding a new
// kind is a deliberate operation: each kind has its own validation +
// matching internal/notifier constructor + matching UI form. Reflection-
// style tag lookup is avoided so the compiler catches every "do I handle
// this kind?" site.
type NotifierKind string

const (
	KindSlack         NotifierKind = "slack"
	KindDiscord       NotifierKind = "discord"
	KindTeams         NotifierKind = "teams"
	KindSMTP          NotifierKind = "smtp"
	KindHomeAssistant NotifierKind = "homeassistant"
	KindNtfy          NotifierKind = "ntfy"
)

// KnownKinds returns the kinds the store currently knows how to validate.
// Anything outside this set is rejected at write time.
func KnownKinds() []NotifierKind {
	return []NotifierKind{KindSlack, KindDiscord, KindTeams, KindSMTP, KindHomeAssistant, KindNtfy}
}

// NotifierEntry is one UI-managed notifier. Per-kind settings live in
// the appropriate optional struct; exactly one of them is populated for
// any given entry (validated by Validate()).
//
// IDs are 16-hex-character strings generated by NewID(); they are
// deliberately not UUIDs (no new dep) but provide enough collision
// resistance for a per-install notifier count.
type NotifierEntry struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Kind      NotifierKind `json:"kind"`
	MinLevel  string       `json:"min_level,omitempty"` // "" defaults to "review" at runtime
	Enabled   bool         `json:"enabled"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`

	Slack         *SlackSettings         `json:"slack,omitempty"`
	Discord       *DiscordSettings       `json:"discord,omitempty"`
	Teams         *TeamsSettings         `json:"teams,omitempty"`
	SMTP          *SMTPSettings          `json:"smtp,omitempty"`
	HomeAssistant *HomeAssistantSettings `json:"homeassistant,omitempty"`
	Ntfy          *NtfySettings          `json:"ntfy,omitempty"`
}

// NtfySettings carries ntfy publish-server fields. ServerURL is the
// base (e.g. "https://ntfy.sh" or "https://ntfy.example.com"); Topic
// is the bare topic name (no leading slash); Token is an optional
// bearer access token issued by the ntfy server.
type NtfySettings struct {
	ServerURL string `json:"server_url"`
	Topic     string `json:"topic"`
	Token     string `json:"token,omitempty"`
}

// SlackSettings carries Slack-specific fields. WebhookURL is the secret;
// Channel optionally overrides the channel the legacy webhooks post to.
type SlackSettings struct {
	WebhookURL string `json:"webhook_url"`
	Channel    string `json:"channel,omitempty"`
}

// DiscordSettings carries Discord-specific fields.
type DiscordSettings struct {
	WebhookURL string `json:"webhook_url"`
}

// TeamsSettings carries Microsoft Teams Incoming Webhook fields.
type TeamsSettings struct {
	WebhookURL string `json:"webhook_url"`
}

// SMTPSettings carries SMTP / e-mail fields.
type SMTPSettings struct {
	Host     string   `json:"host"`
	Port     int      `json:"port"`
	Username string   `json:"username,omitempty"`
	Password string   `json:"password,omitempty"`
	From     string   `json:"from"`
	To       []string `json:"to"`
	TLS      bool     `json:"tls,omitempty"`
}

// HomeAssistantSettings carries Home Assistant REST API fields. Per-level
// dispatch behaviour mirrors the existing yaml `notifications.homeassistant`
// block (Persistent / Push / Critical booleans per risk level).
type HomeAssistantSettings struct {
	URL      string          `json:"url"`
	Token    string          `json:"token"`
	Safe     HALevelDispatch `json:"safe,omitempty"`
	Review   HALevelDispatch `json:"review,omitempty"`
	Breaking HALevelDispatch `json:"breaking,omitempty"`
	Rollback HALevelDispatch `json:"rollback,omitempty"`
}

// HALevelDispatch mirrors internal/config.HANotifyLevel but lives here
// to keep the encrypted store schema decoupled from the YAML schema (so
// either can evolve without breaking on-disk data).
type HALevelDispatch struct {
	Persistent bool `json:"persistent,omitempty"`
	Push       bool `json:"push,omitempty"`
	Critical   bool `json:"critical,omitempty"`
}

// NewID returns a 16-hex-char random identifier suitable for a
// NotifierEntry.ID. Crash-safety: random failures are extremely unlikely
// but bubble up if they do.
func NewID() (string, error) {
	b := make([]byte, 8)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("configstore: id rand: %w", err)
	}
	return hex.EncodeToString(b), nil
}

// Validate checks structural invariants of a NotifierEntry: ID, name,
// kind, min-level shape, and the per-kind required fields.
func (e *NotifierEntry) Validate() error {
	if e == nil {
		return errors.New("notifier entry is nil")
	}
	if e.ID == "" {
		return errors.New("id is required")
	}
	if strings.TrimSpace(e.Name) == "" {
		return errors.New("name is required")
	}
	if e.MinLevel != "" {
		if types.ParseRiskLevel(e.MinLevel) == types.RiskUnknown {
			return fmt.Errorf("min_level %q is not a valid risk level", e.MinLevel)
		}
	}

	switch e.Kind {
	case KindSlack:
		if e.Slack == nil {
			return errors.New("slack settings are required for kind=slack")
		}
		if err := validateWebhookURL("slack.webhook_url", e.Slack.WebhookURL); err != nil {
			return err
		}
		if !nilOthers(e, KindSlack) {
			return errors.New("non-slack settings present on a slack notifier")
		}
	case KindDiscord:
		if e.Discord == nil {
			return errors.New("discord settings are required for kind=discord")
		}
		if err := validateWebhookURL("discord.webhook_url", e.Discord.WebhookURL); err != nil {
			return err
		}
		if !nilOthers(e, KindDiscord) {
			return errors.New("non-discord settings present on a discord notifier")
		}
	case KindTeams:
		if e.Teams == nil {
			return errors.New("teams settings are required for kind=teams")
		}
		if err := validateWebhookURL("teams.webhook_url", e.Teams.WebhookURL); err != nil {
			return err
		}
		if !nilOthers(e, KindTeams) {
			return errors.New("non-teams settings present on a teams notifier")
		}
	case KindSMTP:
		if e.SMTP == nil {
			return errors.New("smtp settings are required for kind=smtp")
		}
		if strings.TrimSpace(e.SMTP.Host) == "" {
			return errors.New("smtp.host is required")
		}
		if e.SMTP.Port <= 0 || e.SMTP.Port > 65535 {
			return fmt.Errorf("smtp.port %d is outside the valid range 1-65535", e.SMTP.Port)
		}
		if strings.TrimSpace(e.SMTP.From) == "" {
			return errors.New("smtp.from is required")
		}
		if len(e.SMTP.To) == 0 {
			return errors.New("smtp.to must contain at least one recipient")
		}
		if !nilOthers(e, KindSMTP) {
			return errors.New("non-smtp settings present on an smtp notifier")
		}
	case KindHomeAssistant:
		if e.HomeAssistant == nil {
			return errors.New("homeassistant settings are required for kind=homeassistant")
		}
		if err := validateAbsoluteURL("homeassistant.url", e.HomeAssistant.URL); err != nil {
			return err
		}
		if strings.TrimSpace(e.HomeAssistant.Token) == "" {
			return errors.New("homeassistant.token is required")
		}
		if !nilOthers(e, KindHomeAssistant) {
			return errors.New("non-homeassistant settings present on a homeassistant notifier")
		}
	case KindNtfy:
		if e.Ntfy == nil {
			return errors.New("ntfy settings are required for kind=ntfy")
		}
		if err := validateAbsoluteURL("ntfy.server_url", e.Ntfy.ServerURL); err != nil {
			return err
		}
		if strings.TrimSpace(e.Ntfy.Topic) == "" {
			return errors.New("ntfy.topic is required")
		}
		if strings.ContainsAny(e.Ntfy.Topic, "/ \t") {
			return fmt.Errorf("ntfy.topic %q must not contain slashes or whitespace", e.Ntfy.Topic)
		}
		if !nilOthers(e, KindNtfy) {
			return errors.New("non-ntfy settings present on an ntfy notifier")
		}
	default:
		return fmt.Errorf("unknown notifier kind %q (known: %v)", e.Kind, KnownKinds())
	}
	return nil
}

func nilOthers(e *NotifierEntry, keep NotifierKind) bool {
	if keep != KindSlack && e.Slack != nil {
		return false
	}
	if keep != KindDiscord && e.Discord != nil {
		return false
	}
	if keep != KindTeams && e.Teams != nil {
		return false
	}
	if keep != KindSMTP && e.SMTP != nil {
		return false
	}
	if keep != KindHomeAssistant && e.HomeAssistant != nil {
		return false
	}
	if keep != KindNtfy && e.Ntfy != nil {
		return false
	}
	return true
}

func validateWebhookURL(field, raw string) error {
	if strings.TrimSpace(raw) == "" {
		return fmt.Errorf("%s is required", field)
	}
	return validateAbsoluteURL(field, raw)
}

func validateAbsoluteURL(field, raw string) error {
	u, err := url.Parse(raw)
	if err != nil {
		return fmt.Errorf("%s is not a valid URL: %w", field, err)
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		return fmt.Errorf("%s must be an http or https URL", field)
	}
	if u.Host == "" {
		return fmt.Errorf("%s must include a host", field)
	}
	return nil
}
